runconfigs-tests: added test to validate rget status in -show-runconfigs and -list-targets

diff --git a/runconfig-tests/tests/rget/rget-check-targets b/runconfig-tests/tests/rget/rget-check-targets
--- a/runconfig-tests/tests/rget/rget-check-targets
+++ b/runconfig-tests/tests/rget/rget-check-targets
@@ -16,6 +16,10 @@ while read line; do
   fi
 done < <(megatest -list-targets)
 
+cstatus=$PIPESTATUS
+[[ $cstatus -gt 0 ]] && \
+  echo "ERROR: COMMAND EXIT STATUS $cstatus"
+
 
 if [[ $found -eq $targets ]]; then
   echo "INFO: Found $targets targets ($found == $targets)"
